# Generated by Django 4.2.9 on 2024-01-22 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house_data',
            name='house_owner_email',
        ),
        migrations.RemoveField(
            model_name='house_data',
            name='house_type',
        ),
    ]
