# Generated by Django 4.2.9 on 2024-01-23 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_remove_house_data_house_owner_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='house_data',
            name='house_code',
            field=models.IntegerField(default=0),
        ),
    ]
