# Generated by Django 4.2.9 on 2024-01-23 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_house_data_house_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house_data',
            name='house_code',
            field=models.IntegerField(default=1, null=True, unique=True),
        ),
    ]
