# Generated by Django 4.2.9 on 2024-01-23 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0005_alter_house_data_house_code_tenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='Tenant_image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='document',
            field=models.FileField(upload_to='documents/'),
        ),
    ]
