# Generated by Django 4.2.9 on 2024-01-23 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0006_alter_tenant_tenant_image_alter_tenant_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='Name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='Phone_No',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
