# Generated by Django 4.2.9 on 2024-01-23 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0007_alter_tenant_name_alter_tenant_phone_no'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tenant',
        ),
    ]
