# Generated by Django 4.2.9 on 2024-01-23 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0009_tenant_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house_data',
            name='house_code',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.DeleteModel(
            name='Tenant_data',
        ),
    ]
