# Generated by Django 4.2.9 on 2024-01-24 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0011_tenant_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant_data',
            name='Meater_Reading',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
