# Generated by Django 4.2.9 on 2024-01-25 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0012_tenant_data_meater_reading'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant_data',
            name='Bill_unit',
            field=models.IntegerField(null=True),
        ),
    ]
