# Generated by Django 4.2.9 on 2024-01-25 17:20

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0013_tenant_data_bill_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant_data',
            name='Additional_Documents',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tenant_data',
            name='Arrived_Month',
            field=models.DateField(null=True),
        ),
    ]
