# Generated by Django 4.2.9 on 2024-01-25 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0014_alter_tenant_data_additional_documents_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant_data',
            name='Email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
