# Generated by Django 4.2.9 on 2024-01-26 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0015_alter_tenant_data_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tenant_data',
        ),
    ]
