# Generated by Django 4.2.9 on 2024-01-26 05:07

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0016_delete_tenant_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, unique=True)),
                ('D_O_B', models.DateField()),
                ('Email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('Phone_No', models.CharField(max_length=10, null=True, unique=True)),
                ('Meater_Reading', models.CharField(blank=True, max_length=100)),
                ('Room_No', models.IntegerField()),
                ('Tenant_image', models.ImageField(upload_to='photos/')),
                ('Work_Place', models.CharField(max_length=100)),
                ('Members', models.IntegerField()),
                ('Rent', models.CharField(max_length=5)),
                ('Advance', models.CharField(max_length=5)),
                ('Arrived_Month', models.DateField()),
                ('Bill_unit', models.IntegerField()),
                ('Documents_Upload', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('House_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.house_data')),
            ],
        ),
    ]
