# Generated by Django 4.2.9 on 2024-01-27 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0017_tenant_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant_data',
            name='Work_Place',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
