# Generated by Django 4.2.9 on 2024-01-27 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0019_tenant_data_members_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant_data',
            name='Address',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
