# Generated by Django 4.2.9 on 2024-01-29 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0020_tenant_data_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.IntegerField()),
                ('Date', models.DateField()),
                ('Mode', models.CharField(max_length=20)),
                ('Payment_Screenshot', models.ImageField(upload_to='payments/')),
                ('Previous_Electricity_Unit', models.IntegerField()),
                ('Current_Electricity_Unit', models.IntegerField()),
                ('Water_Bill', models.IntegerField()),
                ('House_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.house_data')),
                ('Tenant_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.tenant_data')),
            ],
        ),
    ]
