# Generated by Django 4.2.9 on 2024-01-29 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0021_payments_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payments_data',
        ),
    ]
