# Generated by Django 4.2.9 on 2024-02-05 17:01

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0027_alter_payments_data_payment_screenshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Old_record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tenant_Name', models.CharField(max_length=50)),
                ('House_Name', models.CharField(max_length=50)),
                ('D_O_B', models.DateField()),
                ('Rent_Amount', models.IntegerField()),
                ('Date', models.DateField()),
                ('Phone_No', models.IntegerField(max_length=10)),
                ('Tenant_image', models.ImageField(blank=True, upload_to='old_photo/')),
                ('Rent', models.CharField(max_length=5)),
                ('Documents_Upload', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
            ],
        ),
    ]
