# Generated by Django 4.2.9 on 2024-02-05 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0028_old_record'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='old_record',
            name='Rent_Amount',
        ),
    ]
