# Generated by Django 4.2.9 on 2024-02-05 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0029_remove_old_record_rent_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='old_record',
            name='Address',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='old_record',
            name='Email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
