# Generated by Django 4.2.9 on 2024-02-05 17:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0030_old_record_address_old_record_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='old_record',
            name='Date',
            field=models.DateField(default=datetime.date(2024, 2, 5)),
        ),
    ]
