# Generated by Django 4.2.9 on 2024-02-06 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0031_alter_old_record_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Old_record',
        ),
    ]
