# Generated by Django 4.2.9 on 2024-02-06 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0033_old_record'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Old_record',
        ),
    ]
