# Generated by Django 4.2.9 on 2024-02-15 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0037_old_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='old_record',
            name='Email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
