# Generated by Django 4.2.9 on 2024-02-15 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0038_alter_old_record_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='old_payment',
            name='House_Name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='old_payment',
            name='Tenant_Name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
