# Generated by Django 4.2.9 on 2024-02-15 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0040_alter_old_payment_tenant_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Old_payment',
        ),
        migrations.DeleteModel(
            name='Old_record',
        ),
    ]
