# Generated by Django 4.2.9 on 2024-02-17 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0043_alter_old_payment_tenant_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant_data',
            name='Balance',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
