# Generated by Django 4.2.9 on 2024-02-19 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0044_tenant_data_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments_data',
            name='Payment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
